repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.6'
    hooks:
    -   id: clang-format
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
    -   id: yapf
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    -   id: flake8
        args: [--select=F,E71,E9,W1,W6]
